CATEGORY_DESCRIPTIONS = {
    # Astrophysics
    "astro-ph/": "Astrophysics: general astronomy, observational astrophysics, stellar systems, cosmic phenomena, and space observation.",
    "astro-ph.CO/": "Cosmology and Nongalactic Astrophysics: early universe, cosmic microwave background, dark matter, dark energy, galaxy clusters, large-scale structure.",
    "astro-ph.EP/": "Earth and Planetary Astrophysics: exoplanets, solar system dynamics, planetary atmospheres, formation, planetary geology, extrasolar systems.",
    "astro-ph.GA/": "Astrophysics of Galaxies: Milky Way structure, galactic evolution, interstellar medium, active galactic nuclei, star formation in galaxies.",
    "astro-ph.HE/": "High Energy Astrophysical Phenomena: black holes, neutron stars, gamma-ray bursts, cosmic rays, accretion disks, supernovae.",
    "astro-ph.IM/": "Instrumentation and Methods for Astrophysics: astronomical telescopes, detectors, observational methods, data processing algorithms, spectroscopy.",
    "astro-ph.SR/": "Solar and Stellar Astrophysics: sun, solar flares, stellar evolution, stellar spectra, magnetic fields, stellar atmospheres, variable stars.",
    # Condensed Matter
    "cond-mat.dis-nn/": "Disordered Systems and Neural Networks: spin glasses, random media, localization phenomena, neural networks in condensed matter physics.",
    "cond-mat.mes-hall/": "Mesoscale and Nanoscale Physics: quantum dots, 2D materials, quantum Hall effect, nanoscale transport, spintronics, topological insulators.",
    "cond-mat.mtrl-sci/": "Materials Science: crystal structures, mechanical properties, band structure, synthesis, phase transitions, functional materials.",
    "cond-mat.other/": "Other Condensed Matter: emerging topics, novel experimental techniques, soft-matter physics, general condensed matter theory.",
    "cond-mat.quant-gas/": "Quantum Gases: Bose-Einstein condensates, Fermi gases, ultracold atoms, optical lattices, superfluidity in atomic gases.",
    "cond-mat.soft/": "Soft Condensed Matter: polymers, liquid crystals, colloids, membranes, granular media, biological soft matter, complex fluids.",
    "cond-mat.stat-mech/": "Statistical Mechanics: thermodynamic phase transitions, non-equilibrium systems, critical phenomena, fluctuation theorems, kinetic theory.",
    "cond-mat.str-el/": "Strongly Correlated Electrons: high-temperature superconductors, Mott insulators, heavy fermions, quantum magnetism, Hubbard model.",
    "cond-mat.supr-con/": "Superconductivity: superconducting materials, Josephson junctions, BCS theory, flux pinning, high-Tc superconductors.",
    # Computer Science
    "cs.AI": "Artificial Intelligence: machine learning, deep learning, large language models, expert systems, automated reasoning, decision making, neural networks, intelligent agents.",
    "cs.AR/": "Computer Architecture: microprocessor design, memory systems, hardware organization, multiprocessors, instruction sets, hardware acceleration.",
    "cs.CC/": "Computational Complexity: complexity classes like P vs NP, circuit complexity, reduction, hardness, decision problems.",
    "cs.CE/": "Computational Engineering, Finance, and Science: numerical simulations, finite element analysis, scientific computing, computational finance.",
    "cs.CG/": "Computational Geometry: geometric algorithms, convex hulls, Delaunay triangulation, spatial indexes, mesh generation.",
    "cs.CL/": "Computation and Language: natural language processing, speech recognition, machine translation, large language models, computational linguistics.",
    "cs.CR/": "Cryptography and Security: data encryption, network security, authentication, zero-knowledge proofs, system vulnerabilities, privacy.",
    "cs.CV/": "Computer Vision and Pattern Recognition: image classification, object detection, segmentation, optical flow, 3D reconstruction, generative visual models.",
    "cs.CY/": "Computers and Society: privacy policies, social impacts of technology, digital ethics, access, tech policy, human factors.",
    "cs.DB/": "Databases: relational databases, query optimization, NoSQL, transaction management, data indexing, database storage engines.",
    "cs.DC/": "Distributed, Parallel, and Cluster Computing: cloud computing, parallel algorithms, consensus protocols, distributed systems, map-reduce.",
    "cs.DL/": "Digital Libraries: institutional repositories, metadata schemes, citation analysis, document archiving, digital curation.",
    "cs.DM/": "Discrete Mathematics: graph theory, combinatorics, graph algorithms, discrete optimization, network flow.",
    "cs.DS/": "Data Structures and Algorithms: algorithm design, dynamic programming, sorting, searching, space and time complexity bounds.",
    "cs.ET/": "Emerging Technologies: quantum computing architecture, DNA computing, neuromorphic hardware, novel computing paradigms.",
    "cs.FL/": "Formal Languages and Automata Theory: regular expressions, context-free grammars, Turing machines, language parsing, automata theory.",
    "cs.GL/": "General Literature: introductory survey papers, computing histories, broad overviews, general computer science discussions.",
    "cs.GR/": "Computer Graphics: rendering, ray tracing, GPU shaders, animation, physical simulation, procedural generation, rasterization.",
    "cs.GT/": "Computer Science and Game Theory: algorithmic game theory, mechanism design, auction theory, Nash equilibria, multi-agent economics.",
    "cs.HC/": "Human-Computer Interaction: user interface design, UX usability studies, accessibility, user testing, interactive systems.",
    "cs.IR/": "Information Retrieval: search engines, document ranking, vector space models, recommendation systems, text mining.",
    "cs.IT/": "Information Theory: Shannon entropy, channel capacity, error-correcting codes, rate-distortion theory, signal compression.",
    "cs.LG/": "Machine Learning: deep learning, supervised learning, reinforcement learning, feature representation, generative models, optimization algorithms.",
    "cs.LO/": "Logic in Computer Science: formal logic, automated theorem proving, type theory, modal logic, model checking, program semantics.",
    "cs.MA/": "Multiagent Systems: agent interaction, distributed coordination, swarms, cooperative behaviors, multi-agent reinforcement learning.",
    "cs.MM/": "Multimedia: audio processing, video compression, streaming protocols, multimodal data integration, media codecs.",
    "cs.MS/": "Mathematical Software: numerical libraries, computer algebra systems, software packages for matrix calculations.",
    "cs.NA/": "Numerical Analysis: numerical linear algebra, ODE solvers, error analysis, root finding, matrix factorizations.",
    "cs.NE/": "Neural and Evolutionary Computing: genetic algorithms, evolutionary strategies, spiking neural networks, neuroevolution.",
    "cs.NI/": "Networking and Internet Architecture: TCP/IP protocols, wireless networks, software-defined networking, network routing, latency.",
    "cs.OH/": "Other Computer Science: miscellaneous computer science topics not classified elsewhere.",
    "cs.OS/": "Operating Systems: kernel design, process scheduling, memory management, file systems, virtualization, concurrency.",
    "cs.PF/": "Performance: benchmarking, profiling, system throughput, bottleneck analysis, performance evaluation.",
    "cs.PL/": "Programming Languages: compiler construction, type systems, language semantics, functional programming, static analysis.",
    "cs.RO/": "Robotics: kinematic planning, motion control, SLAM, autonomous navigation, robotic manipulators, perception.",
    "cs.SC/": "Symbolic Computation: computer algebra, polynomial factorization, exact symbolic calculations, symbolic integration.",
    "cs.SD/": "Sound: audio signal processing, speech synthesis, acoustic modeling, sound analysis, music information retrieval.",
    "cs.SE/": "Software Engineering: software testing, DevOps, refactoring, software architecture, bug detection, code maintenance.",
    "cs.SI/": "Social and Information Networks: graph metrics, community detection, network centrality, rumor propagation, social media analysis.",
    "cs.SY/": "Systems and Control: control systems, feedback loops, state-space analysis, optimal control, cyber-physical systems.",
    # Economics & EESS
    "econ.EM/": "Econometrics: statistical methods in economics, regression models, time series analysis, causal inference, empirical economics.",
    "econ.TH/": "Theoretical Economics: microeconomic theory, game theory, general equilibrium, incentive alignment, market design.",
    "eess.SY/": "Systems and Control: dynamical systems theory, control system engineering, feedback systems, state estimation, stability theory.",
    # General Relativity & Quantum Cosmology
    "gr-qc/": "General Relativity and Quantum Cosmology: gravitational waves, black hole physics, Einstein field equations, cosmology, quantum gravity.",
    # High Energy Physics
    "hep-ex/": "High Energy Physics - Experiment: particle accelerator experiments, collider physics, particle detectors, LHC results.",
    "hep-lat/": "High Energy Physics - Lattice: lattice quantum chromodynamics (QCD), lattice field theory, non-perturbative calculations.",
    "hep-ph/": "High Energy Physics - Phenomenology: Standard Model extensions, Higgs physics, neutrino oscillations, dark matter candidates, collider phenomenology.",
    "hep-th/": "High Energy Physics - Theory: quantum field theory, string theory, supersymmetry, conformal field theory, gauge theories.",
    # Mathematical Physics
    "math-ph/": "Mathematical Physics: rigorous mathematical formulations of physical models, classical field theories, operator algebras in physics.",
    # Mathematics
    "math.AC/": "Commutative Algebra: rings, ideals, modules, commutative algebra, Gröbner bases, homological algebra.",
    "math.AG/": "Algebraic Geometry: algebraic varieties, schemes, sheaves, birational geometry, algebraic curves and surfaces.",
    "math.AP/": "Analysis of PDEs: partial differential equations, Sobolev spaces, wave equations, Navier-Stokes, elliptic operators.",
    "math.AT/": "Algebraic Topology: homotopy theory, homology groups, persistent homology, fiber bundles, topological spaces.",
    "math.CA/": "Classical Analysis and ODEs: special functions, ordinary differential equations, harmonic analysis, orthogonal polynomials.",
    "math.CO/": "Combinatorics: graph theory, enumerative combinatorics, design theory, extremal combinatorics, posets.",
    "math.CT/": "Category Theory: functors, monads, natural transformations, topoi, category-theoretic foundations.",
    "math.CV/": "Complex Variables: complex analysis, several complex variables, Riemann surfaces, holomorphic functions, complex manifolds.",
    "math.DG/": "Differential Geometry: Riemannian manifolds, differential forms, Ricci flow, curvature, symplectic manifolds.",
    "math.DS/": "Dynamical Systems: chaos theory, ergodic theory, topological dynamics, bifurcations, strange attractors.",
    "math.FA/": "Functional Analysis: Hilbert spaces, Banach spaces, spectral theory of operators, C*-algebras, distribution theory.",
    "math.GM/": "General Mathematics: elementary mathematics, educational mathematics, general mathematical expositions.",
    "math.GN/": "General Topology: point-set topology, topological vector spaces, metric spaces, compactness, connectedness.",
    "math.GR/": "Group Theory: finite groups, Lie groups, representation of groups, free groups, geometric group theory.",
    "math.GT/": "Geometric Topology: 3-manifolds, 4-manifolds, knot theory, braid groups, low-dimensional topology.",
    "math.HO/": "History and Overview: history of mathematics, survey papers, mathematical biography, expository articles.",
    "math.IT/": "Information Theory: mathematical fundamentals of coding theory, channel capacity, information inequalities.",
    "math.KT/": "K-Theory and Homology: algebraic K-theory, operator K-theory, cyclic homology, Grothendieck groups.",
    "math.LO/": "Logic: mathematical logic, model theory, set theory, proof theory, computability theory.",
    "math.MG/": "Metric Geometry: metric spaces, Alexandrov geometry, Gromov-Hausdorff distance, optimal transport.",
    "math.MP/": "Mathematical Physics: rigorous methods in quantum mechanics, theoretical mechanics, mathematical relativity.",
    "math.NA/": "Numerical Analysis: mathematical analysis of numerical algorithms, error bounds, convergence of numerical methods.",
    "math.NT/": "Number Theory: prime numbers, modular forms, diophantine equations, analytic number theory, algebraic number theory.",
    "math.OA/": "Operator Algebras: von Neumann algebras, C*-algebras, non-commutative geometry, operator spaces.",
    "math.OC/": "Optimization and Control: convex optimization, optimal control theory, calculus of variations, non-linear programming.",
    "math.PR/": "Probability: stochastic processes, Brownian motion, random matrices, limit theorems, measure-theoretic probability.",
    "math.QA/": "Quantum Algebra: quantum groups, Hopf algebras, non-commutative geometry, quantum invariants.",
    "math.RA/": "Rings and Algebras: non-commutative rings, associative algebras, Lie algebras, non-associative structures.",
    "math.RT/": "Representation Theory: representations of groups, Lie algebras, associative algebras, character theory.",
    "math.SG/": "Symplectic Geometry: symplectic manifolds, Hamiltonian dynamics, Floer homology, contact geometry.",
    "math.SP/": "Spectral Theory: eigenvalues, differential operators, Schrödinger operators, spectral measures.",
    "math.ST/": "Statistics Theory: mathematical statistics, estimation theory, hypothesis testing, asymptotic statistics.",
    # Nonlinear Sciences
    "nlin.AO/": "Adaptation and Self-Organizing Systems: complex systems, multi-agent adaptation, genetic algorithms in physics, self-organization.",
    "nlin.CD/": "Chaotic Dynamics: nonlinear dynamics, Lyapunov exponents, strange attractors, period doubling, chaos theory.",
    "nlin.CG/": "Cellular Automata and Lattice Gases: cellular automata rules, lattice Boltzmann methods, discrete spatial models.",
    "nlin.PS/": "Pattern Formation and Solitons: solitary waves, nonlinear Schrödinger equation, reaction-diffusion systems, spatio-temporal dynamics.",
    "nlin.SI/": "Exactly Solvable and Integrable Systems: integrable systems, Lax pairs, Painlevé equations, inverse scattering transform.",
    # Nuclear Physics
    "nucl-ex/": "Nuclear Experiment: experimental nuclear structure, heavy-ion collisions, nuclear reactions, radioactive beams.",
    "nucl-th/": "Nuclear Theory: nuclear force, shell model, dense nuclear matter, relativistic heavy-ion theory, QCD in nuclei.",
    # Physics
    "physics.acc-ph/": "Accelerator Physics: particle accelerators, beam dynamics, synchrotrons, RF cavities, beam instrumentation.",
    "physics.ao-ph/": "Atmospheric and Oceanic Physics: meteorology, ocean dynamics, climate science, atmospheric turbulence, fluid mechanics.",
    "physics.app-ph/": "Applied Physics: semiconductors, device physics, applied electromagnetics, sensor technology.",
    "physics.atm-clus/": "Atomic and Molecular Clusters: cluster physics, nanoparticle formation, molecular aggregates.",
    "physics.atom-ph/": "Atomic Physics: laser cooling, atomic spectroscopy, Rydberg states, atomic collisions, precision measurements.",
    "physics.bio-ph/": "Biological Physics: biophysics, protein folding, molecular motors, DNA mechanics, cellular mechanics.",
    "physics.chem-ph/": "Chemical Physics: quantum chemistry, molecular dynamics, reaction kinetics, vibrational spectroscopy.",
    "physics.class-ph/": "Classical Physics: classical mechanics, electrodynamics, wave propagation, classical field theory.",
    "physics.comp-ph/": "Computational Physics: Monte Carlo simulations, numerical PDEs in physics, molecular dynamics algorithms.",
    "physics.data-an/": "Data Analysis, Statistics and Probability: experimental data processing, parameter estimation, statistical methods in physics.",
    "physics.ed-ph/": "Physics Education: pedagogy, physics teaching methods, laboratory education, physics curriculum design.",
    "physics.flu-dyn/": "Fluid Dynamics: turbulence, Navier-Stokes, boundary layers, aerodynamics, multiphase flows.",
    "physics.gen-ph/": "General Physics: broad physical concepts, foundational topics, general physics surveys.",
    "physics.geo-ph/": "Geophysics: seismology, geomagnetism, plate tectonics, mantle convection, geodynamics.",
    "physics.hist-ph/": "History and Philosophy of Physics: history of science, philosophical foundations of quantum mechanics and relativity.",
    "physics.ins-det/": "Instrumentation and Detectors: particle detectors, radiation sensors, signal amplification, readout electronics.",
    "physics.med-ph/": "Medical Physics: radiation therapy, MRI imaging, PET scans, dosimetry, medical imaging processing.",
    "physics.optics/": "Optics: lasers, photonics, non-linear optics, fiber optics, wave propagation, optical metamaterials.",
    "physics.plasm-ph/": "Plasma Physics: magnetohydrodynamics, fusion energy, Tokamaks, laser-plasma interactions, space plasmas.",
    "physics.pop-ph/": "Popular Physics: science communication, layperson physics, popular science expositions.",
    "physics.soc-ph/": "Physics and Society: econophysics, sociophysics, network dynamics in social systems, opinion dynamics.",
    "physics.space-ph/": "Space Physics: magnetosphere, solar wind, ionosphere, space weather, heliosphere.",
    # Quantitative Biology
    "q-bio.BM/": "Biomolecules: biomolecular structure, protein structure prediction, RNA/DNA folding, molecular modeling.",
    "q-bio.CB/": "Cell Behavior: cell signaling pathways, cell division, cell motility, intracellular transport, cell-cell interaction.",
    "q-bio.GN/": "Genomics: genome sequencing, gene expression analysis, functional genomics, comparative genomics, bioinformatics.",
    "q-bio.MN/": "Molecular Networks: gene regulatory networks, metabolic pathways, protein-protein interaction networks.",
    "q-bio.NC/": "Neurons and Cognition: computational neuroscience, neural encoding, spiking neural models, brain dynamics.",
    "q-bio.OT/": "Other Quantitative Biology: emerging biological topics, novel quantitative methods, general biocomputation.",
    "q-bio.PE/": "Populations and Evolution: population genetics, evolutionary dynamics, phylogenetics, epidemiology models.",
    "q-bio.QM/": "Quantitative Methods: mathematical modeling in biology, statistical bioanalysis, biological image processing.",
    "q-bio.SC/": "Subcellular Processes: organelle dynamics, membrane transport, single-molecule biophysics.",
    "q-bio.TO/": "Tissues and Organs: tissue mechanics, organogenesis, physiological modeling, circulatory dynamics.",
    # Quantitative Finance
    "q-fin.CP/": "Computational Finance: numerical option pricing, Monte Carlo pricing models, financial algorithmic design.",
    "q-fin.GN/": "General Finance: financial markets overview, macroeconomic finance theory, general market studies.",
    "q-fin.PM/": "Portfolio Management: asset allocation, portfolio optimization, risk-adjusted returns, factor investing.",
    "q-fin.PR/": "Pricing of Securities: options, futures, derivatives pricing, term structure of interest rates.",
    "q-fin.RM/": "Risk Management: Value at Risk (VaR), credit risk modeling, market risk assessment, stress testing.",
    "q-fin.ST/": "Statistical Finance: high-frequency trading data, financial time series analysis, volatility clustering, heavy-tailed distributions.",
    "q-fin.TR/": "Trading and Market Microstructure: order book dynamics, market liquidity, execution algorithms, market impact.",
    # Quantum Physics
    "quant-ph/": "Quantum Physics: quantum information, quantum computing, quantum entanglement, quantum algorithms, quantum optics, decoherence.",
    # Statistics
    "stat.AP/": "Applications: applied statistics, real-world data analysis, biostatistics, environmental statistics.",
    "stat.CO/": "Computation: Markov Chain Monte Carlo (MCMC), expectation-maximization algorithm, computational statistics, bootstrap methods.",
    "stat.ME/": "Methodology: statistical modeling, regression techniques, survival analysis, spatial statistics, causal inference.",
    "stat.ML/": "Machine Learning: statistical machine learning, PAC learning, high-dimensional inference, kernel methods, generalization bounds.",
    "stat.OT/": "Other Statistics: foundational statistics, statistical philosophy, miscellaneous statistical topics.",
    "stat.TH/": "Theory: mathematical statistics theory, asymptotic distribution theory, decision theory, Bayesian foundations.",
}


USER_FRIENDLY_NAMES = {
    # Astrophysics
    "astro-ph": "Astrophysics",
    "astro-ph.CO": "Cosmology and Nongalactic Astrophysics",
    "astro-ph.EP": "Earth and Planetary Astrophysics",
    "astro-ph.GA": "Astrophysics of Galaxies",
    "astro-ph.HE": "High Energy Astrophysical Phenomena",
    "astro-ph.IM": "Instrumentation and Methods for Astrophysics",
    "astro-ph.SR": "Solar and Stellar Astrophysics",
    # Condensed Matter
    "cond-mat.dis-nn": "Disordered Systems and Neural Networks",
    "cond-mat.mes-hall": "Mesoscale and Nanoscale Physics",
    "cond-mat.mtrl-sci": "Materials Science",
    "cond-mat.other": "Other Condensed Matter",
    "cond-mat.quant-gas": "Quantum Gases",
    "cond-mat.soft": "Soft Condensed Matter",
    "cond-mat.stat-mech": "Statistical Mechanics",
    "cond-mat.str-el": "Strongly Correlated Electrons",
    "cond-mat.supr-con": "Superconductivity",
    # Computer Science
    "cs.AI": "Artificial Intelligence",
    "cs.AR": "Computer Architecture",
    "cs.CC": "Computational Complexity",
    "cs.CE": "Computational Engineering, Finance, and Science",
    "cs.CG": "Computational Geometry",
    "cs.CL": "Computation and Language (NLP)",
    "cs.CR": "Cryptography and Security",
    "cs.CV": "Computer Vision and Pattern Recognition",
    "cs.CY": "Computers and Society",
    "cs.DB": "Databases",
    "cs.DC": "Distributed, Parallel, and Cluster Computing",
    "cs.DL": "Digital Libraries",
    "cs.DM": "Discrete Mathematics",
    "cs.DS": "Data Structures and Algorithms",
    "cs.ET": "Emerging Technologies",
    "cs.FL": "Formal Languages and Automata Theory",
    "cs.GL": "General Literature",
    "cs.GR": "Computer Graphics",
    "cs.GT": "Computer Science and Game Theory",
    "cs.HC": "Human-Computer Interaction",
    "cs.IR": "Information Retrieval",
    "cs.IT": "Information Theory (CS)",
    "cs.LG": "Machine Learning (CS)",
    "cs.LO": "Logic in Computer Science",
    "cs.MA": "Multiagent Systems",
    "cs.MM": "Multimedia",
    "cs.MS": "Mathematical Software",
    "cs.NA": "Numerical Analysis (CS)",
    "cs.NE": "Neural and Evolutionary Computing",
    "cs.NI": "Networking and Internet Architecture",
    "cs.OH": "Other Computer Science",
    "cs.OS": "Operating Systems",
    "cs.PF": "Performance",
    "cs.PL": "Programming Languages",
    "cs.RO": "Robotics",
    "cs.SC": "Symbolic Computation",
    "cs.SD": "Sound",
    "cs.SE": "Software Engineering",
    "cs.SI": "Social and Information Networks",
    "cs.SY": "Systems and Control (CS)",
    # Economics & EESS
    "econ.EM": "Econometrics",
    "econ.TH": "Theoretical Economics",
    "eess.SY": "Systems and Control (EESS)",
    # General Relativity & Quantum Cosmology
    "gr-qc": "General Relativity and Quantum Cosmology",
    # High Energy Physics
    "hep-ex": "High Energy Physics - Experiment",
    "hep-lat": "High Energy Physics - Lattice",
    "hep-ph": "High Energy Physics - Phenomenology",
    "hep-th": "High Energy Physics - Theory",
    # Mathematical Physics
    "math-ph": "Mathematical Physics",
    # Mathematics
    "math.AC": "Commutative Algebra",
    "math.AG": "Algebraic Geometry",
    "math.AP": "Analysis of PDEs",
    "math.AT": "Algebraic Topology",
    "math.CA": "Classical Analysis and ODEs",
    "math.CO": "Combinatorics",
    "math.CT": "Category Theory",
    "math.CV": "Complex Variables",
    "math.DG": "Differential Geometry",
    "math.DS": "Dynamical Systems",
    "math.FA": "Functional Analysis",
    "math.GM": "General Mathematics",
    "math.GN": "General Topology",
    "math.GR": "Group Theory",
    "math.GT": "Geometric Topology",
    "math.HO": "History and Overview",
    "math.IT": "Information Theory (Math)",
    "math.KT": "K-Theory and Homology",
    "math.LO": "Logic",
    "math.MG": "Metric Geometry",
    "math.MP": "Mathematical Physics (Math)",
    "math.NA": "Numerical Analysis (Math)",
    "math.NT": "Number Theory",
    "math.OA": "Operator Algebras",
    "math.OC": "Optimization and Control",
    "math.PR": "Probability",
    "math.QA": "Quantum Algebra",
    "math.RA": "Rings and Algebras",
    "math.RT": "Representation Theory",
    "math.SG": "Symplectic Geometry",
    "math.SP": "Spectral Theory",
    "math.ST": "Statistics Theory (Math)",
    # Nonlinear Sciences
    "nlin.AO": "Adaptation and Self-Organizing Systems",
    "nlin.CD": "Chaotic Dynamics",
    "nlin.CG": "Cellular Automata and Lattice Gases",
    "nlin.PS": "Pattern Formation and Solitons",
    "nlin.SI": "Exactly Solvable and Integrable Systems",
    # Nuclear Physics
    "nucl-ex": "Nuclear Experiment",
    "nucl-th": "Nuclear Theory",
    # Physics
    "physics.acc-ph": "Accelerator Physics",
    "physics.ao-ph": "Atmospheric and Oceanic Physics",
    "physics.app-ph": "Applied Physics",
    "physics.atm-clus": "Atomic and Molecular Clusters",
    "physics.atom-ph": "Atomic Physics",
    "physics.bio-ph": "Biological Physics",
    "physics.chem-ph": "Chemical Physics",
    "physics.class-ph": "Classical Physics",
    "physics.comp-ph": "Computational Physics",
    "physics.data-an": "Data Analysis, Statistics and Probability",
    "physics.ed-ph": "Physics Education",
    "physics.flu-dyn": "Fluid Dynamics",
    "physics.gen-ph": "General Physics",
    "physics.geo-ph": "Geophysics",
    "physics.hist-ph": "History and Philosophy of Physics",
    "physics.ins-det": "Instrumentation and Detectors",
    "physics.med-ph": "Medical Physics",
    "physics.optics": "Optics",
    "physics.plasm-ph": "Plasma Physics",
    "physics.pop-ph": "Popular Physics",
    "physics.soc-ph": "Physics and Society",
    "physics.space-ph": "Space Physics",
    # Quantitative Biology
    "q-bio.BM": "Biomolecules",
    "q-bio.CB": "Cell Behavior",
    "q-bio.GN": "Genomics",
    "q-bio.MN": "Molecular Networks",
    "q-bio.NC": "Neurons and Cognition",
    "q-bio.OT": "Other Quantitative Biology",
    "q-bio.PE": "Populations and Evolution",
    "q-bio.QM": "Quantitative Methods",
    "q-bio.SC": "Subcellular Processes",
    "q-bio.TO": "Tissues and Organs",
    # Quantitative Finance
    "q-fin.CP": "Computational Finance",
    "q-fin.GN": "General Finance",
    "q-fin.PM": "Portfolio Management",
    "q-fin.PR": "Pricing of Securities",
    "q-fin.RM": "Risk Management",
    "q-fin.ST": "Statistical Finance",
    "q-fin.TR": "Trading and Market Microstructure",
    # Quantum Physics
    "quant-ph": "Quantum Physics",
    # Statistics
    "stat.AP": "Applications",
    "stat.CO": "Computation",
    "stat.ME": "Methodology",
    "stat.ML": "Machine Learning (Stats)",
    "stat.OT": "Other Statistics",
    "stat.TH": "Theory (Stats)",
}
